### ISSUE TITLE
Gallery feature improvements

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#3]
I think the gallery has to much shadows. Does not look that good with the rest of the design.

How about this:
![image](https://cloud.githubusercontent.com/assets/1503577/15454126/83320e50-202f-11e6-9a77-f304f37994c8.png)

insted of this:
![image](https://cloud.githubusercontent.com/assets/1503577/15454151/172caf0c-2030-11e6-9541-93f519130a7c.png)

new css (background & border is same as the bg from code tag): 

``` css
.single-post .album {
    height: 400px;
    white-space: nowrap;
    /* background: rgb(204, 204, 204); */
    padding: 20px;
    background: rgba(250,250,250,0.8);
    border-top: 1px solid #eeeeee;
    border-bottom: 1px solid #eeeeee;
    /* -webkit-box-shadow: 0 -2px 5px rgba(0,0,0,0.5) inset,0 2px 5px rgba(0,0,0,0.5) inset; */
    /*  -moz-box-shadow: 0 -2px 5px rgba(0,0,0,0.5) inset,0 2px 5px rgba(0,0,0,0.5) inset; */
    /* box-shadow: 0 -2px 5px rgba(0,0,0,0.5) inset,0 2px 5px rgba(0,0,0,0.5) inset; */
    overflow-x: auto;
    overflow-y: hidden;
    margin: 30px 0;
}

.single-post .album img {
    display: inline-block;
    height: 100%;
    width: auto;
    border: 3px solid rgba(255,255,255,0.5);
    -webkit-box-shadow: 0 3px 5px rgba(0,0,0,0.5);
    -moz-box-shadow: 0 3px 5px rgba(0,0,0,0.5);
    /* box-shadow: 0 3px 5px rgba(0,0,0,0.5); */
    margin: 0 10px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    cursor: pointer;
}
```
