### ISSUE TITLE
Scroll top style

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#5]
Not a problem with the current css only that i like the scroll top button more if it is round and have a small opacity. With the current button it feels a little bit to much of an obstical that distracts from the content. Please take a look and decide yourself:

![image](https://cloud.githubusercontent.com/assets/1503577/15454217/489f368e-2032-11e6-9905-71cf6af3a06a.png)

CSS:

``` css
.go-to-top {
    background-image: url("../assets/go-to-top.png");
    width: 40px;
    height: 40px;
    position: fixed;
    bottom: 30px;
    right: 100px;
    border: none;
    display: none;
    border-radius: 25px;
    opacity: 0.6;
}
```
